version: '3.1'

services:

  db:
    container_name: mysql-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t
    ports:
      - 3306:3306

  adminer:
    container_name: adminer-mysql-db
    image: adminer
    restart: always
    ports:
      - 8080:8080